### ISSUE TITLE
issue with @import insturctions

### ISSUE THREAD

**Issue by NitsanBaleli** [datorama/themify#6]
trying to 
`@import 'node_modules/datorama/themify/dist/themify';`

results in 
`File to import not found or unreadable: node_modules/datorama/themify/dist/themify.`

workaround:
`@import 'node_modules/@datorama/themify/themify';`

am I missing something or is this a mistake in the guide?

I'd be happy to open a PR if this is indeed a mistake

**Comment by NetanelBasal** [comment]
Yes, there is a mistake. It should be `node_modules/@datorama/themify/themify';`. Fixed. Thanks.
